### ISSUE TITLE
Float is not a double

### ISSUE THREAD

**Issue by kafkiansky** [typhoon-php/typhoon#54]
I'm using typhoon for binary serialization and it's important for me to distinguish `float` from `double` as they have different binary layouts (4 bytes vs 8 bytes). [This](https://github.com/typhoon-php/typhoon/blob/0.4.x/src/Reflection/Internal/PhpDoc/ContextualPhpDocTypeReflector.php#L135) code treats them as one type. Could you please introduce `types::double`?

**Comment by vudaltsov** [comment]
Hi! Thank you for the issue. I know that float is not a double. The problem is that in PHP [they are considered to be the same](https://www.php.net/manual/en/language.types.float.php). PHPStan also uses `double` as an alias for `float` (see https://github.com/phpstan/phpstan/issues/214).

We might consider introducing `types::double`, `types::double()` and `TypeVisitor::double()`, `TypeVisitor::doubleValue()` as first-class citizens, but that would require some understanding of how we will support them in other tools in future.

For now I would suggest creating a `class Double (float $value) {}` and then using `types::object(Double::class)`. You can even have your own collection of binary enum types:

```php
enum binaryTypes implements Type
{
    case int8;
    case int16;
    case int32;
    case int64;
    case double;

    public function accept(TypeVisitor $visitor): mixed
    {
        return match ($this) {
            self::int8 => $visitor->namedObject($this, Id::namedClass(Int8::class), []),
            self::int16 => $visitor->namedObject($this, Id::namedClass(Int16::class), []),
            self::int32 => $visitor->namedObject($this, Id::namedClass(Int32::class), []),
            self::int64 => $visitor->namedObject($this, Id::namedClass(Int64::class), []),
            self::double => $visitor->namedObject($this, Id::namedClass(Double::class), []),
        };
    }
}
```

WDYT?

**Comment by vudaltsov** [comment]
Done in https://github.com/typhoon-php/typhoon/commit/fe25e895dfdaa7b8884ebb9c927d7a16c8790880, https://github.com/typhoon-php/typhoon/commit/456058ebda3ca3ff683529245c27de908a782fba. See https://github.com/typhoon-php/typhoon/blob/0.4.x/docs/implementing_custom_types.md for docs.
